### ISSUE TITLE
Not really an issue, a question

### ISSUE THREAD

**Issue by Tobster88** [PixelRick/HZD_PC_Gamer_Camera#3]
Hi. First of all, thank you for making this and potentially making a lot of playthroughs more convenient and less nauseating.

Does the executable need to be used upon every game start, or is it a one-time thing?

Cheers!

**Comment by Tobster88** [comment]
It does need to be used every time you start the game.

**Comment by PixelRick** [comment]
Hi, sorry for the late answer. Yes it needs to be run every time, it has the advantage of not breaking the update process of your game since it doesn't touch the game files on disk. If an update breaks it, don't hesitate to tell me, because I'm not actively playing any game these days.
