### ISSUE TITLE
Remaster version

### ISSUE THREAD

**Issue by FoxPurple** [PixelRick/HZD_PC_Gamer_Camera#8]
Heyo i know this is 3 years old but is there a way to get a updated version for the remaster?

**Comment by PixelRick** [comment]
I'll try in the coming days.

**Comment by FoxPurple** [comment]
Thanks man, that's super awesome. My motion sickness thanks you

**Comment by PixelRick** [comment]
Support added with last commit 3d77ffd. I tested myself but not extensively.
If you find a bug or need tweaks, please open a new issue (one is open for left/right shoulder cam).
edit: sorry for the delay of ~12 days, I had a 7 day technical test for a job application then a planned game festival with friends :/
